# Site settings
title: "Blog technique"
header-img: "assets/img/header/home-bg.jpg"
email: lahaxe.arnaud@gmail.com
description: ""
baseurl: ""
url: "http://test.lahaxe.fr"
twitter_username: lahaxe_arnaud
github_username:  lahaxearnaud

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 7
exclude: ["assets/less","node_modules","Gruntfile.js","package.json","README.md"]
